site_name: GeaFlow Docs

theme: 
    name: readthedocs

plugins:
  - include-markdown

nav:
  - '中文导航页': 'index_cn.md'
  - '中文文档':
    - 'geaflow简介': 'docs-cn/introduction.md'
    - '快速上手': 'docs-cn/quick_start.md'
    - '概念':
      - 'glossary': 'docs-cn/concepts/glossary.md'
    


python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
