site_name: GeaFlow Docs

theme: readthedocs

plugins:
  - include-markdown

nav:
  - GeaFlow 中文文档导航页: 
        - index_cn.md
        - GeaFlow简介: docs-cn/introduction.md
        - 快速上手(本地运行): docs-cn/quick_start.md
        - 开始上手(GeaFlow Console运行): docs-cn/quick_start_docker.md
        - 概念:
              - 名称解释: docs-cn/concepts/glossary.md
              - Graph View: docs-cn/concepts/graph_view.md
              - Stream Graph: docs-cn/concepts/stream_graph.md
        - GeaFlow应用开发:
              - API:
                    -API介绍: docs-cn/application-development/api/overview.md
                    -Guid: docs-cn/application-development/api/guid.md
                    - 图:
                          - Compute API介绍: docs-cn/application-development/api/graph/compute.md
                          - Traversal API介绍: docs-cn/application-development/api/graph/traversal.md
                    - 流:
                          - Process API介绍: docs-cn/application-development/api/stream/process.md
                          - Sink API介绍: docs-cn/application-development/api/stream/sink.md
                          - Source API介绍: docs-cn/application-development/api/stream/source.md
              - DSL:
                    - 融合DSL概述: docs-cn/application-development/dsl/overview.md
                    - 内置函数:
                          - aggregate: docs-cn/application-development/dsl/build-in/aggregate.md
                          - condition: docs-cn/application-development/dsl/build-in/condition.md
                          - date: docs-cn/application-development/dsl/build-in/date.md
                          - logical: docs-cn/application-development/dsl/build-in/logical.md
                          - math: docs-cn/application-development/dsl/build-in/math.md
                          - string: docs-cn/application-development/dsl/build-in/string.md
                          - table: docs-cn/application-development/dsl/build-in/table.md
                    - 连接器(Connector):
                          - common: docs-cn/application-development/dsl/connector/common.md
                          - file: docs-cn/application-development/dsl/connector/file.md
                          - console: docs-cn/application-development/dsl/connector/console.md
                          - jdbc: docs-cn/application-development/dsl/connector/jdbc.md
                          - hive: docs-cn/application-development/dsl/connector/hive.md
                          - kafka: docs-cn/application-development/dsl/connector/kafka.md
                          - hbase: docs-cn/application-development/dsl/connector/hbase.md
                          - hudi: docs-cn/application-development/dsl/connector/hudi.md
                          - udc: docs-cn/application-development/dsl/connector/udc.md
                    - 语法文档:
                          - 'docs-cn/application-development/dsl/reference/ddl.md'
                          - 'docs-cn/application-development/dsl/reference/dml.md'
                          - DQL:
                                - 'docs-cn/application-development/dsl/reference/dql/match.md'
                                - 'docs-cn/application-development/dsl/reference/dql/select.md'
                                - 'docs-cn/application-development/dsl/reference/dql/union.md'
                                - 'docs-cn/application-development/dsl/reference/dql/with.md'
                          - 'docs-cn/application-development/dsl/reference/use.md'
                    - UDF:
                          - 'docs-cn/application-development/dsl/udf/udaf.md'
                          - 'docs-cn/application-development/dsl/udf/udf.md'
                          - 'docs-cn/application-development/dsl/udf/udga.md'
                          - 'docs-cn/application-development/dsl/udf/udtf.md'
        - 部署:
              - 'docs-cn/deploy/install_guide.md'
        - 原理:
              - 'docs-cn/principle/dsl_principle.md'
              - 'docs-cn/principle/framework_principle.md'
              - 'docs-cn/principle/state_principle.md'
              - 'docs-cn/principle/vs_join.md'
        - './docs-cn/contribution.md'

  - 'index.md'
  - English Document:
    - 'docs-en/introduction.md'
    - 'docs-en/quick_start.md'
    - 'docs-en/quick_start_docker.md'
    - Concepts:
        - 'docs-en/concepts/glossary.md'
        - 'docs-en/concepts/graph_view.md'
        - 'docs-en/concepts/stream_graph.md'
    - Application-Development:
        - API:
            - 'docs-en/application-development/api/overview.md'
            - 'docs-en/application-development/api/guid.md'
            - Graph:
                - 'docs-en/application-development/api/graph/compute.md'
                - 'docs-en/application-development/api/graph/traversal.md'
            - Stream:
                - 'docs-en/application-development/api/stream/process.md'
                - 'docs-en/application-development/api/stream/sink.md'
                - 'docs-en/application-development/api/stream/source.md'
        - DSL:
            - 'docs-en/application-development/dsl/overview.md'
            - Build-In:
                - 'docs-en/application-development/dsl/build-in/aggregate.md'
                - 'docs-en/application-development/dsl/build-in/condition.md'
                - 'docs-en/application-development/dsl/build-in/date.md'
                - 'docs-en/application-development/dsl/build-in/logical.md'
                - 'docs-en/application-development/dsl/build-in/math.md'
                - 'docs-en/application-development/dsl/build-in/string.md'
                - 'docs-en/application-development/dsl/build-in/table.md'
            - Connector:
                - 'docs-en/application-development/dsl/connector/common.md'
                - 'docs-en/application-development/dsl/connector/file.md'
                - 'docs-en/application-development/dsl/connector/console.md'
                - 'docs-en/application-development/dsl/connector/jdbc.md'
                - 'docs-en/application-development/dsl/connector/hive.md'
                - 'docs-en/application-development/dsl/connector/kafka.md'
                - 'docs-en/application-development/dsl/connector/hbase.md'
                - 'docs-en/application-development/dsl/connector/hudi.md'
                - 'docs-en/application-development/dsl/connector/udc.md'
            - Reference:
                - 'docs-en/application-development/dsl/reference/ddl.md'
                - 'docs-en/application-development/dsl/reference/dml.md'
                - DQL:
                  - 'docs-en/application-development/dsl/reference/dql/match.md'
                  - 'docs-en/application-development/dsl/reference/dql/select.md'
                  - 'docs-en/application-development/dsl/reference/dql/union.md'
                  - 'docs-en/application-development/dsl/reference/dql/with.md'
                - 'docs-en/application-development/dsl/reference/use.md'
            - UDF:
                - 'docs-en/application-development/dsl/udf/udaf.md'
                - 'docs-en/application-development/dsl/udf/udf.md'
                - 'docs-en/application-development/dsl/udf/udga.md'
                - 'docs-en/application-development/dsl/udf/udtf.md'
    - Deploy:
        - 'docs-en/deploy/install_guide.md'
    - Principle:
        - 'docs-en/principle/dsl_principle.md'
        - 'docs-en/principle/framework_principle.md'
        - 'docs-en/principle/state_principle.md'
        - 'docs-en/principle/vs_join.md'
    - './docs-en/contribution.md'

markdown_extensions:
  - toc:
      toc_depth: 4

python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
