site_name: GeaFlow Docs

theme: 
    name: readthedocs

plugins:
  - include-markdown

nav:
  - Home: 'index_cn.md'

markdown_extensions:
  - toc:
      toc_depth: 4

python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
