site_name: GeaFlow Docs

theme: readthedocs

plugins:
  - include-markdown

nav:
  - 中文导航: 'index.md'
  - 详细文档:
      - 简介: 'docs-cn/introduction.md'
      - 启动: 'docs-cn/quick_start.md'
  - 概念:
    - glossar: 'docs-cn/concepts/glossary.md'

markdown_extensions:
  - toc:
      toc_depth: 4

python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
