site_name: GeaFlow Docs

theme:
  name: readthedocs
  nav_style: dark

plugins:
  - include-markdown

nav:
  - 'index_cn.md'
    - 'docs-cn/introduction.md'
    - 'docs-cn/quick_start.md'
    - 'docs-cn/quick_start_docker.md'
    - 概念: 
      - 'docs-cn/concepts/glossary.md'
      - 'docs-cn/concepts/graph_view.md'
      - 'docs-cn/concepts/stream_graph.md'
    - GeaFlow应用开发:
      - API:
        - 'docs-cn/application-development/api/overview.md'
        - 'docs-cn/application-development/api/guid.md'
        - 图:
          - 'docs-cn/application-development/api/graph/compute.md'
          - 'docs-cn/application-development/api/graph/traversal.md'
        - 流:
          - 'docs-cn/application-development/api/stream/process.md'
          - 'docs-cn/application-development/api/stream/sink.md'
          - 'docs-cn/application-development/api/stream/source.md'
       - DSL:
         - 'docs-cn/application-development/dsl/overview.md'
         - 内置函数:
           - 'docs-cn/application-development/dsl/build-in/aggregate.md'
           - 'docs-cn/application-development/dsl/build-in/condition.md'
           - 'docs-cn/application-development/dsl/build-in/date.md'
           - 'docs-cn/application-development/dsl/build-in/logical.md'
           - 'docs-cn/application-development/dsl/build-in/math.md'
           - 'docs-cn/application-development/dsl/build-in/string.md'
           - 'docs-cn/application-development/dsl/build-in/table.md'
             - 连接器(Connector):
               - 'docs-cn/application-development/dsl/connector/common.md'
               - 'docs-cn/application-development/dsl/connector/file.md'
               - 'docs-cn/application-development/dsl/connector/console.md'
               - 'docs-cn/application-development/dsl/connector/jdbc.md'
               - 'docs-cn/application-development/dsl/connector/hive.md'
               - 'docs-cn/application-development/dsl/connector/kafka.md'
               - 'docs-cn/application-development/dsl/connector/hbase.md'
               - 'docs-cn/application-development/dsl/connector/hudi.md'
               - 'docs-cn/application-development/dsl/connector/udc.md'
            - 语法文档:
              - 'docs-cn/application-development/dsl/reference/ddl.md'
              - 'docs-cn/application-development/dsl/reference/dml.md'
              - DQL:
                - 'docs-cn/application-development/dsl/reference/dql/match.md'
                - 'docs-cn/application-development/dsl/reference/dql/select.md'
                - 'docs-cn/application-development/dsl/reference/dql/union.md'
                - 'docs-cn/application-development/dsl/reference/dql/with.md'
                - 'docs-cn/application-development/dsl/reference/use.md'
            - UDF:
              - 'docs-cn/application-development/dsl/udf/udaf.md'
              - 'docs-cn/application-development/dsl/udf/udf.md'
              - 'docs-cn/application-development/dsl/udf/udga.md'
              - 'docs-cn/application-development/dsl/udf/udtf.md'
    - 部署:
      - 'docs-cn/deploy/install_guide.md'
    - 原理:
      - 'docs-cn/principle/dsl_principle.md'
      - 'docs-cn/principle/framework_principle.md'
      - 'docs-cn/principle/state_principle.md'
      - 'docs-cn/principle/vs_join.md'
    - './docs-cn/contribution.md'


python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
