site_name: GeaFlow Docs

theme: 
    name: readthedocs

plugins:
  - include-markdown

nav:
  - Home: 'index_cn.md'
  - '简介':
      - 'docs-cn/introduction.md' 
      - 'docs-cn/quick_start.md'
      - 'docs-cn/quick_start_docker.md'
  - 概念:
      - 'docs-cn/concepts/glossary.md'
      - 'docs-cn/concepts/graph_view.md'
      - 'docs-cn/concepts/stream_graph.md'
  - GeaFlow应用开发:
      - API:
          - 'docs-cn/application-development/api/overview.md'
          - 'docs-cn/application-development/api/guid.md'
          - 图:
              - 'docs-cn/application-development/api/graph/compute.md'
              - 'docs-cn/application-development/api/graph/traversal.md'
                  - 流:
                      - 'docs-cn/application-development/api/stream/process.md'
                      - 'docs-cn/application-development/api/stream/sink.md'
                      - 'docs-cn/application-development/api/stream/source.md'
        

markdown_extensions:
  - toc:
      toc_depth: 4

python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0
