/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metaserver.proto

package org.apache.geaflow.rpc.proto;

public final class MetaServer {
    private MetaServer() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ServiceRequestPbOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ServiceRequestPb)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes request = 1;</code>
         */
        com.google.protobuf.ByteString getRequest();
    }

    /**
     * Protobuf type {@code ServiceRequestPb}
     */
    public static final class ServiceRequestPb extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ServiceRequestPb)
        ServiceRequestPbOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ServiceRequestPb.newBuilder() to construct.
        private ServiceRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ServiceRequestPb() {
            request_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new ServiceRequestPb();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ServiceRequestPb(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            request_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MetaServer.internal_static_ServiceRequestPb_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MetaServer.internal_static_ServiceRequestPb_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    MetaServer.ServiceRequestPb.class, MetaServer.ServiceRequestPb.Builder.class);
        }

        public static final int REQUEST_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString request_;

        /**
         * <code>bytes request = 1;</code>
         */
        public com.google.protobuf.ByteString getRequest() {
            return request_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (!request_.isEmpty()) {
                output.writeBytes(1, request_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!request_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(1, request_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MetaServer.ServiceRequestPb)) {
                return super.equals(obj);
            }
            MetaServer.ServiceRequestPb other = (MetaServer.ServiceRequestPb) obj;

            if (!getRequest()
                .equals(other.getRequest())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REQUEST_FIELD_NUMBER;
            hash = (53 * hash) + getRequest().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceRequestPb parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceRequestPb parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MetaServer.ServiceRequestPb parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceRequestPb parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceRequestPb parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MetaServer.ServiceRequestPb prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServiceRequestPb}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ServiceRequestPb)
            MetaServer.ServiceRequestPbOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MetaServer.internal_static_ServiceRequestPb_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MetaServer.internal_static_ServiceRequestPb_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        MetaServer.ServiceRequestPb.class, MetaServer.ServiceRequestPb.Builder.class);
            }

            // Construct using com.antgroup.geaflow.rpc.proto.MetaServer.ServiceRequestPb.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                request_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MetaServer.internal_static_ServiceRequestPb_descriptor;
            }

            @java.lang.Override
            public MetaServer.ServiceRequestPb getDefaultInstanceForType() {
                return MetaServer.ServiceRequestPb.getDefaultInstance();
            }

            @java.lang.Override
            public MetaServer.ServiceRequestPb build() {
                MetaServer.ServiceRequestPb result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MetaServer.ServiceRequestPb buildPartial() {
                MetaServer.ServiceRequestPb result = new MetaServer.ServiceRequestPb(this);
                result.request_ = request_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MetaServer.ServiceRequestPb) {
                    return mergeFrom((MetaServer.ServiceRequestPb) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MetaServer.ServiceRequestPb other) {
                if (other == MetaServer.ServiceRequestPb.getDefaultInstance()) return this;
                if (other.getRequest() != com.google.protobuf.ByteString.EMPTY) {
                    setRequest(other.getRequest());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                MetaServer.ServiceRequestPb parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MetaServer.ServiceRequestPb) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes request = 1;</code>
             */
            public com.google.protobuf.ByteString getRequest() {
                return request_;
            }

            /**
             * <code>bytes request = 1;</code>
             */
            public Builder setRequest(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                request_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes request = 1;</code>
             */
            public Builder clearRequest() {

                request_ = getDefaultInstance().getRequest();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ServiceRequestPb)
        }

        // @@protoc_insertion_point(class_scope:ServiceRequestPb)
        private static final MetaServer.ServiceRequestPb DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MetaServer.ServiceRequestPb();
        }

        public static MetaServer.ServiceRequestPb getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ServiceRequestPb>
            PARSER = new com.google.protobuf.AbstractParser<ServiceRequestPb>() {
            @java.lang.Override
            public ServiceRequestPb parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServiceRequestPb(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ServiceRequestPb> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ServiceRequestPb> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MetaServer.ServiceRequestPb getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ServiceResultPbOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ServiceResultPb)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes result = 1;</code>
         */
        com.google.protobuf.ByteString getResult();
    }

    /**
     * Protobuf type {@code ServiceResultPb}
     */
    public static final class ServiceResultPb extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ServiceResultPb)
        ServiceResultPbOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ServiceResultPb.newBuilder() to construct.
        private ServiceResultPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ServiceResultPb() {
            result_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new ServiceResultPb();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ServiceResultPb(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            result_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MetaServer.internal_static_ServiceResultPb_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MetaServer.internal_static_ServiceResultPb_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    MetaServer.ServiceResultPb.class, MetaServer.ServiceResultPb.Builder.class);
        }

        public static final int RESULT_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString result_;

        /**
         * <code>bytes result = 1;</code>
         */
        public com.google.protobuf.ByteString getResult() {
            return result_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (!result_.isEmpty()) {
                output.writeBytes(1, result_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!result_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(1, result_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MetaServer.ServiceResultPb)) {
                return super.equals(obj);
            }
            MetaServer.ServiceResultPb other = (MetaServer.ServiceResultPb) obj;

            if (!getResult()
                .equals(other.getResult())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + getResult().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MetaServer.ServiceResultPb parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceResultPb parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MetaServer.ServiceResultPb parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MetaServer.ServiceResultPb parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceResultPb parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static MetaServer.ServiceResultPb parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MetaServer.ServiceResultPb prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServiceResultPb}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ServiceResultPb)
            MetaServer.ServiceResultPbOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MetaServer.internal_static_ServiceResultPb_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MetaServer.internal_static_ServiceResultPb_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        MetaServer.ServiceResultPb.class, MetaServer.ServiceResultPb.Builder.class);
            }

            // Construct using com.antgroup.geaflow.rpc.proto.MetaServer.ServiceResultPb.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                result_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MetaServer.internal_static_ServiceResultPb_descriptor;
            }

            @java.lang.Override
            public MetaServer.ServiceResultPb getDefaultInstanceForType() {
                return MetaServer.ServiceResultPb.getDefaultInstance();
            }

            @java.lang.Override
            public MetaServer.ServiceResultPb build() {
                MetaServer.ServiceResultPb result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MetaServer.ServiceResultPb buildPartial() {
                MetaServer.ServiceResultPb result = new MetaServer.ServiceResultPb(this);
                result.result_ = result_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MetaServer.ServiceResultPb) {
                    return mergeFrom((MetaServer.ServiceResultPb) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MetaServer.ServiceResultPb other) {
                if (other == MetaServer.ServiceResultPb.getDefaultInstance()) return this;
                if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
                    setResult(other.getResult());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                MetaServer.ServiceResultPb parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MetaServer.ServiceResultPb) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes result = 1;</code>
             */
            public com.google.protobuf.ByteString getResult() {
                return result_;
            }

            /**
             * <code>bytes result = 1;</code>
             */
            public Builder setResult(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes result = 1;</code>
             */
            public Builder clearResult() {

                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ServiceResultPb)
        }

        // @@protoc_insertion_point(class_scope:ServiceResultPb)
        private static final MetaServer.ServiceResultPb DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MetaServer.ServiceResultPb();
        }

        public static MetaServer.ServiceResultPb getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ServiceResultPb>
            PARSER = new com.google.protobuf.AbstractParser<ServiceResultPb>() {
            @java.lang.Override
            public ServiceResultPb parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServiceResultPb(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ServiceResultPb> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ServiceResultPb> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MetaServer.ServiceResultPb getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_ServiceRequestPb_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_ServiceRequestPb_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_ServiceResultPb_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_ServiceResultPb_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\020metaserver.proto\"#\n\020ServiceRequestPb\022\017" +
                "\n\007request\030\001 \001(\014\"!\n\017ServiceResultPb\022\016\n\006re" +
                "sult\030\001 \001(\014B.\n\036com.antgroup.geaflow.rpc.p" +
                "rotoB\nMetaServerP\000b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                });
        internal_static_ServiceRequestPb_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_ServiceRequestPb_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ServiceRequestPb_descriptor,
            new java.lang.String[]{"Request",});
        internal_static_ServiceResultPb_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_ServiceResultPb_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ServiceResultPb_descriptor,
            new java.lang.String[]{"Result",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
