/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view_meta.proto

package org.apache.geaflow.view.meta;

public final class ViewMetaPb {
    private ViewMetaPb() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ViewMetaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ViewMeta)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */
        int getKvInfoCount();

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */
        boolean containsKvInfo(
            java.lang.String key);

        /**
         * Use {@link #getKvInfoMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getKvInfo();

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */
        java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getKvInfoMap();

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        com.google.protobuf.ByteString getKvInfoOrDefault(
            java.lang.String key,
            com.google.protobuf.ByteString defaultValue);

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        com.google.protobuf.ByteString getKvInfoOrThrow(
            java.lang.String key);
    }

    /**
     * Protobuf type {@code ViewMeta}
     */
    public static final class ViewMeta extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ViewMeta)
        ViewMetaOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ViewMeta.newBuilder() to construct.
        private ViewMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ViewMeta() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new ViewMeta();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ViewMeta(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                kvInfo_ = com.google.protobuf.MapField.newMapField(
                                    KvInfoDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                                kvInfo__ = input.readMessage(
                                KvInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            kvInfo_.getMutableMap().put(
                                kvInfo__.getKey(), kvInfo__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ViewMetaPb.internal_static_ViewMeta_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
            switch (number) {
                case 1:
                    return internalGetKvInfo();
                default:
                    throw new RuntimeException(
                        "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ViewMetaPb.internal_static_ViewMeta_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    ViewMetaPb.ViewMeta.class, ViewMetaPb.ViewMeta.Builder.class);
        }

        public static final int KVINFO_FIELD_NUMBER = 1;

        private static final class KvInfoDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                java.lang.String, com.google.protobuf.ByteString> defaultEntry =
                com.google.protobuf.MapEntry
                    .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                        ViewMetaPb.internal_static_ViewMeta_KvInfoEntry_descriptor,
                        com.google.protobuf.WireFormat.FieldType.STRING,
                        "",
                        com.google.protobuf.WireFormat.FieldType.BYTES,
                        com.google.protobuf.ByteString.EMPTY);
        }

        private com.google.protobuf.MapField<
            java.lang.String, com.google.protobuf.ByteString> kvInfo_;

        private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetKvInfo() {
            if (kvInfo_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                    KvInfoDefaultEntryHolder.defaultEntry);
            }
            return kvInfo_;
        }

        public int getKvInfoCount() {
            return internalGetKvInfo().getMap().size();
        }

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        public boolean containsKvInfo(
            java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetKvInfo().getMap().containsKey(key);
        }

        /**
         * Use {@link #getKvInfoMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKvInfo() {
            return getKvInfoMap();
        }

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKvInfoMap() {
            return internalGetKvInfo().getMap();
        }

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        public com.google.protobuf.ByteString getKvInfoOrDefault(
            java.lang.String key,
            com.google.protobuf.ByteString defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetKvInfo().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
         */

        public com.google.protobuf.ByteString getKvInfoOrThrow(
            java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                internalGetKvInfo().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                    output,
                    internalGetKvInfo(),
                    KvInfoDefaultEntryHolder.defaultEntry,
                    1);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
                : internalGetKvInfo().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                    kvInfo__ = KvInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
                size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, kvInfo__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ViewMetaPb.ViewMeta)) {
                return super.equals(obj);
            }
            ViewMetaPb.ViewMeta other = (ViewMetaPb.ViewMeta) obj;

            if (!internalGetKvInfo().equals(
                other.internalGetKvInfo())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetKvInfo().getMap().isEmpty()) {
                hash = (37 * hash) + KVINFO_FIELD_NUMBER;
                hash = (53 * hash) + internalGetKvInfo().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ViewMetaPb.ViewMeta parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ViewMetaPb.ViewMeta parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ViewMetaPb.ViewMeta parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static ViewMetaPb.ViewMeta parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static ViewMetaPb.ViewMeta parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ViewMetaPb.ViewMeta prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ViewMeta}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ViewMeta)
            ViewMetaPb.ViewMetaOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ViewMetaPb.internal_static_ViewMeta_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                int number) {
                switch (number) {
                    case 1:
                        return internalGetKvInfo();
                    default:
                        throw new RuntimeException(
                            "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableKvInfo();
                    default:
                        throw new RuntimeException(
                            "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ViewMetaPb.internal_static_ViewMeta_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        ViewMetaPb.ViewMeta.class, ViewMetaPb.ViewMeta.Builder.class);
            }

            // Construct using org.apache.geaflow.view.meta.ViewMetaPb.ViewMeta.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                internalGetMutableKvInfo().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ViewMetaPb.internal_static_ViewMeta_descriptor;
            }

            @java.lang.Override
            public ViewMetaPb.ViewMeta getDefaultInstanceForType() {
                return ViewMetaPb.ViewMeta.getDefaultInstance();
            }

            @java.lang.Override
            public ViewMetaPb.ViewMeta build() {
                ViewMetaPb.ViewMeta result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public ViewMetaPb.ViewMeta buildPartial() {
                ViewMetaPb.ViewMeta result = new ViewMetaPb.ViewMeta(this);
                result.kvInfo_ = internalGetKvInfo();
                result.kvInfo_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ViewMetaPb.ViewMeta) {
                    return mergeFrom((ViewMetaPb.ViewMeta) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ViewMetaPb.ViewMeta other) {
                if (other == ViewMetaPb.ViewMeta.getDefaultInstance()) return this;
                internalGetMutableKvInfo().mergeFrom(
                    other.internalGetKvInfo());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                ViewMetaPb.ViewMeta parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ViewMetaPb.ViewMeta) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.MapField<
                java.lang.String, com.google.protobuf.ByteString> kvInfo_;

            private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
            internalGetKvInfo() {
                if (kvInfo_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                        KvInfoDefaultEntryHolder.defaultEntry);
                }
                return kvInfo_;
            }

            private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
            internalGetMutableKvInfo() {
                onChanged();
                if (kvInfo_ == null) {
                    kvInfo_ = com.google.protobuf.MapField.newMapField(
                        KvInfoDefaultEntryHolder.defaultEntry);
                }
                if (!kvInfo_.isMutable()) {
                    kvInfo_ = kvInfo_.copy();
                }
                return kvInfo_;
            }

            public int getKvInfoCount() {
                return internalGetKvInfo().getMap().size();
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public boolean containsKvInfo(
                java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetKvInfo().getMap().containsKey(key);
            }

            /**
             * Use {@link #getKvInfoMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKvInfo() {
                return getKvInfoMap();
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKvInfoMap() {
                return internalGetKvInfo().getMap();
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public com.google.protobuf.ByteString getKvInfoOrDefault(
                java.lang.String key,
                com.google.protobuf.ByteString defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                    internalGetKvInfo().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public com.google.protobuf.ByteString getKvInfoOrThrow(
                java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
                    internalGetKvInfo().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearKvInfo() {
                internalGetMutableKvInfo().getMutableMap()
                    .clear();
                return this;
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public Builder removeKvInfo(
                java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableKvInfo().getMutableMap()
                    .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
            getMutableKvInfo() {
                return internalGetMutableKvInfo().getMutableMap();
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */
            public Builder putKvInfo(
                java.lang.String key,
                com.google.protobuf.ByteString value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableKvInfo().getMutableMap()
                    .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, bytes&gt; kvInfo = 1;</code>
             */

            public Builder putAllKvInfo(
                java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
                internalGetMutableKvInfo().getMutableMap()
                    .putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ViewMeta)
        }

        // @@protoc_insertion_point(class_scope:ViewMeta)
        private static final ViewMetaPb.ViewMeta DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ViewMetaPb.ViewMeta();
        }

        public static ViewMetaPb.ViewMeta getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ViewMeta>
            PARSER = new com.google.protobuf.AbstractParser<ViewMeta>() {
            @java.lang.Override
            public ViewMeta parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new ViewMeta(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ViewMeta> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ViewMeta> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public ViewMetaPb.ViewMeta getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_ViewMeta_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_ViewMeta_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_ViewMeta_KvInfoEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_ViewMeta_KvInfoEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\014view_meta.pb\"`\n\010ViewMeta\022%\n\006kvInfo\030\001 \003" +
                "(\0132\025.ViewMeta.KvInfoEntry\032-\n\013KvInfoEntry" +
                "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001B \n\036com." +
                "antgroup.geaflow.view.metab\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                });
        internal_static_ViewMeta_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_ViewMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ViewMeta_descriptor,
            new java.lang.String[]{"KvInfo",});
        internal_static_ViewMeta_KvInfoEntry_descriptor =
            internal_static_ViewMeta_descriptor.getNestedTypes().get(0);
        internal_static_ViewMeta_KvInfoEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ViewMeta_KvInfoEntry_descriptor,
            new java.lang.String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
