name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  JAVA_TOOL_OPTIONS: -Xmx3g

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print available memory
        run: free -m

      - name: Set time zone
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Setup Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "21.7"

      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy --toolchain nightly

      - name: Build CStore
        run: |
          cd geaflow-cstore
          touch ~/.cstore_buildrc && make features mod=0 && source ~/.cstore_buildrc
          cd java && ./build.sh
        env:
          OSTYPE: Linux

      - name: CStore Test
        run: |
          cd geaflow-cstore
          make all

      - name: Build and Test
        run: mvn -B -e clean test -Duser.timezone=Asia/Shanghai
